<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AssemblyName>USB-of_on</AssemblyName>
    <RootNamespace>USBofon</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Prefer32Bit>false</Prefer32Bit>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Product>USB-of_on</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

</Project>
