<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AssemblyName>USB-of_on</AssemblyName>
    <RootNamespace>USBofon</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Prefer32Bit>false</Prefer32Bit>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Product>USB-of_on</Product>
    <Version>1.5.0</Version>
    <ApplicationIcon>..\..\assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\icon.png" LogicalName="img.icon.png" />
    <EmbeddedResource Include="..\..\assets\links\*.png" LogicalName="img.%(Filename).png" />
  </ItemGroup>

</Project>
